/**
 * Gila E-Commerce API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuditLogDto { 
    /**
     * Unique identifier of the audit log record
     */
    id?: string;
    /**
     * Log event occurrence timestamp
     */
    timestamp?: string;
    /**
     * Username who performed the action
     */
    username?: string;
    /**
     * Action description category
     */
    actionType?: string;
    /**
     * Action status (e.g. SUCCESS, FAILURE)
     */
    status?: string;
    /**
     * Additional transaction metadata details
     */
    details?: { [key: string]: any; };
}

