/**
 * Gila E-Commerce API
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ChatbotRequestDto { 
    /**
     * The query message to the chatbot assistant
     */
    message: string;
}
