/**
 * Gila E-Commerce API
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ChatbotResponseDto { 
    /**
     * The formatted reply from the chatbot assistant
     */
    reply: string;
}
