/**
 * Gila E-Commerce API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ImportProducts202Response { 
    /**
     * Unique identifier of the queued import task
     */
    taskId?: string;
    /**
     * Initial status of the task
     */
    status?: string;
}

