/**
 * Gila E-Commerce API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderItemDto } from './orderItemDto';


export interface OrderDto { 
    id: string;
    status: string;
    totalPrice: number;
    items: Array<OrderItemDto>;
    createdAt: string;
}

