name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  frontend:
    uses: ./.github/workflows/frontend.yml

  backend:
    needs: frontend
    uses: ./.github/workflows/backend.yml
